const ENDPOINT_TWITTER_SEARCH_TWEETS = 'search/tweets';
const ENDPOINT_TWITTER_POST_UPDATE_TWEET = 'statuses/update';
const ENDPOINT_TWITTER_RETWEET = 'statuses/retweet/:id';
const ENDPOINT_TWITTER_POST_MEDIA = 'media/upload';

module.exports = {
    ENDPOINT_TWITTER_SEARCH_TWEETS,
    ENDPOINT_TWITTER_POST_UPDATE_TWEET,
    ENDPOINT_TWITTER_RETWEET,
    ENDPOINT_TWITTER_POST_MEDIA
}